// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// BPointerCalculator is an autogenerated mock type for the BPointerCalculator type
type BPointerCalculator struct {
	mock.Mock
}

type BPointerCalculator_Expecter struct {
	mock *mock.Mock
}

func (_m *BPointerCalculator) EXPECT() *BPointerCalculator_Expecter {
	return &BPointerCalculator_Expecter{mock: &_m.Mock}
}

// FindBPointer provides a mock function with given fields: date
func (_m *BPointerCalculator) FindBPointer(date *time.Time) int {
	ret := _m.Called(date)

	var r0 int
	if rf, ok := ret.Get(0).(func(*time.Time) int); ok {
		r0 = rf(date)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// BPointerCalculator_FindBPointer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBPointer'
type BPointerCalculator_FindBPointer_Call struct {
	*mock.Call
}

// FindBPointer is a helper method to define mock.On call
//   - date *time.Time
func (_e *BPointerCalculator_Expecter) FindBPointer(date interface{}) *BPointerCalculator_FindBPointer_Call {
	return &BPointerCalculator_FindBPointer_Call{Call: _e.mock.On("FindBPointer", date)}
}

func (_c *BPointerCalculator_FindBPointer_Call) Run(run func(date *time.Time)) *BPointerCalculator_FindBPointer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*time.Time))
	})
	return _c
}

func (_c *BPointerCalculator_FindBPointer_Call) Return(_a0 int) *BPointerCalculator_FindBPointer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BPointerCalculator_FindBPointer_Call) RunAndReturn(run func(*time.Time) int) *BPointerCalculator_FindBPointer_Call {
	_c.Call.Return(run)
	return _c
}

// FindBPointerIncludingDay provides a mock function with given fields: date
func (_m *BPointerCalculator) FindBPointerIncludingDay(date *time.Time) int {
	ret := _m.Called(date)

	var r0 int
	if rf, ok := ret.Get(0).(func(*time.Time) int); ok {
		r0 = rf(date)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// BPointerCalculator_FindBPointerIncludingDay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBPointerIncludingDay'
type BPointerCalculator_FindBPointerIncludingDay_Call struct {
	*mock.Call
}

// FindBPointerIncludingDay is a helper method to define mock.On call
//   - date *time.Time
func (_e *BPointerCalculator_Expecter) FindBPointerIncludingDay(date interface{}) *BPointerCalculator_FindBPointerIncludingDay_Call {
	return &BPointerCalculator_FindBPointerIncludingDay_Call{Call: _e.mock.On("FindBPointerIncludingDay", date)}
}

func (_c *BPointerCalculator_FindBPointerIncludingDay_Call) Run(run func(date *time.Time)) *BPointerCalculator_FindBPointerIncludingDay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*time.Time))
	})
	return _c
}

func (_c *BPointerCalculator_FindBPointerIncludingDay_Call) Return(_a0 int) *BPointerCalculator_FindBPointerIncludingDay_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BPointerCalculator_FindBPointerIncludingDay_Call) RunAndReturn(run func(*time.Time) int) *BPointerCalculator_FindBPointerIncludingDay_Call {
	_c.Call.Return(run)
	return _c
}

// FindBPointerModiferForDayOfWeek provides a mock function with given fields: date
func (_m *BPointerCalculator) FindBPointerModiferForDayOfWeek(date *time.Time) int {
	ret := _m.Called(date)

	var r0 int
	if rf, ok := ret.Get(0).(func(*time.Time) int); ok {
		r0 = rf(date)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// BPointerCalculator_FindBPointerModiferForDayOfWeek_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBPointerModiferForDayOfWeek'
type BPointerCalculator_FindBPointerModiferForDayOfWeek_Call struct {
	*mock.Call
}

// FindBPointerModiferForDayOfWeek is a helper method to define mock.On call
//   - date *time.Time
func (_e *BPointerCalculator_Expecter) FindBPointerModiferForDayOfWeek(date interface{}) *BPointerCalculator_FindBPointerModiferForDayOfWeek_Call {
	return &BPointerCalculator_FindBPointerModiferForDayOfWeek_Call{Call: _e.mock.On("FindBPointerModiferForDayOfWeek", date)}
}

func (_c *BPointerCalculator_FindBPointerModiferForDayOfWeek_Call) Run(run func(date *time.Time)) *BPointerCalculator_FindBPointerModiferForDayOfWeek_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*time.Time))
	})
	return _c
}

func (_c *BPointerCalculator_FindBPointerModiferForDayOfWeek_Call) Return(_a0 int) *BPointerCalculator_FindBPointerModiferForDayOfWeek_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BPointerCalculator_FindBPointerModiferForDayOfWeek_Call) RunAndReturn(run func(*time.Time) int) *BPointerCalculator_FindBPointerModiferForDayOfWeek_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewBPointerCalculator interface {
	mock.TestingT
	Cleanup(func())
}

// NewBPointerCalculator creates a new instance of BPointerCalculator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBPointerCalculator(t mockConstructorTestingTNewBPointerCalculator) *BPointerCalculator {
	mock := &BPointerCalculator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
