// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	models "github.com/keldonia/btime.go/models"
	mock "github.com/stretchr/testify/mock"
)

// BStringUtil is an autogenerated mock type for the BStringUtil type
type BStringUtil struct {
	mock.Mock
}

type BStringUtil_Expecter struct {
	mock *mock.Mock
}

func (_m *BStringUtil) EXPECT() *BStringUtil_Expecter {
	return &BStringUtil_Expecter{mock: &_m.Mock}
}

// DecimalToBString provides a mock function with given fields: decimal
func (_m *BStringUtil) DecimalToBString(decimal float64) string {
	ret := _m.Called(decimal)

	var r0 string
	if rf, ok := ret.Get(0).(func(float64) string); ok {
		r0 = rf(decimal)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// BStringUtil_DecimalToBString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecimalToBString'
type BStringUtil_DecimalToBString_Call struct {
	*mock.Call
}

// DecimalToBString is a helper method to define mock.On call
//   - decimal float64
func (_e *BStringUtil_Expecter) DecimalToBString(decimal interface{}) *BStringUtil_DecimalToBString_Call {
	return &BStringUtil_DecimalToBString_Call{Call: _e.mock.On("DecimalToBString", decimal)}
}

func (_c *BStringUtil_DecimalToBString_Call) Run(run func(decimal float64)) *BStringUtil_DecimalToBString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(float64))
	})
	return _c
}

func (_c *BStringUtil_DecimalToBString_Call) Return(_a0 string) *BStringUtil_DecimalToBString_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BStringUtil_DecimalToBString_Call) RunAndReturn(run func(float64) string) *BStringUtil_DecimalToBString_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateBString provides a mock function with given fields: appt
func (_m *BStringUtil) GenerateBString(appt *models.Appointment) (*string, error) {
	ret := _m.Called(appt)

	var r0 *string
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.Appointment) (*string, error)); ok {
		return rf(appt)
	}
	if rf, ok := ret.Get(0).(func(*models.Appointment) *string); ok {
		r0 = rf(appt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	if rf, ok := ret.Get(1).(func(*models.Appointment) error); ok {
		r1 = rf(appt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BStringUtil_GenerateBString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateBString'
type BStringUtil_GenerateBString_Call struct {
	*mock.Call
}

// GenerateBString is a helper method to define mock.On call
//   - appt *models.Appointment
func (_e *BStringUtil_Expecter) GenerateBString(appt interface{}) *BStringUtil_GenerateBString_Call {
	return &BStringUtil_GenerateBString_Call{Call: _e.mock.On("GenerateBString", appt)}
}

func (_c *BStringUtil_GenerateBString_Call) Run(run func(appt *models.Appointment)) *BStringUtil_GenerateBString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Appointment))
	})
	return _c
}

func (_c *BStringUtil_GenerateBString_Call) Return(_a0 *string, _a1 error) *BStringUtil_GenerateBString_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BStringUtil_GenerateBString_Call) RunAndReturn(run func(*models.Appointment) (*string, error)) *BStringUtil_GenerateBString_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateBStringFromAppointments provides a mock function with given fields: appointments
func (_m *BStringUtil) GenerateBStringFromAppointments(appointments *[]models.Appointment) (*[]string, error) {
	ret := _m.Called(appointments)

	var r0 *[]string
	var r1 error
	if rf, ok := ret.Get(0).(func(*[]models.Appointment) (*[]string, error)); ok {
		return rf(appointments)
	}
	if rf, ok := ret.Get(0).(func(*[]models.Appointment) *[]string); ok {
		r0 = rf(appointments)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]string)
		}
	}

	if rf, ok := ret.Get(1).(func(*[]models.Appointment) error); ok {
		r1 = rf(appointments)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BStringUtil_GenerateBStringFromAppointments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateBStringFromAppointments'
type BStringUtil_GenerateBStringFromAppointments_Call struct {
	*mock.Call
}

// GenerateBStringFromAppointments is a helper method to define mock.On call
//   - appointments *[]models.Appointment
func (_e *BStringUtil_Expecter) GenerateBStringFromAppointments(appointments interface{}) *BStringUtil_GenerateBStringFromAppointments_Call {
	return &BStringUtil_GenerateBStringFromAppointments_Call{Call: _e.mock.On("GenerateBStringFromAppointments", appointments)}
}

func (_c *BStringUtil_GenerateBStringFromAppointments_Call) Run(run func(appointments *[]models.Appointment)) *BStringUtil_GenerateBStringFromAppointments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*[]models.Appointment))
	})
	return _c
}

func (_c *BStringUtil_GenerateBStringFromAppointments_Call) Return(_a0 *[]string, _a1 error) *BStringUtil_GenerateBStringFromAppointments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BStringUtil_GenerateBStringFromAppointments_Call) RunAndReturn(run func(*[]models.Appointment) (*[]string, error)) *BStringUtil_GenerateBStringFromAppointments_Call {
	_c.Call.Return(run)
	return _c
}

// ParseBString provides a mock function with given fields: bString
func (_m *BStringUtil) ParseBString(bString string) (*int64, error) {
	ret := _m.Called(bString)

	var r0 *int64
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*int64, error)); ok {
		return rf(bString)
	}
	if rf, ok := ret.Get(0).(func(string) *int64); ok {
		r0 = rf(bString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int64)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(bString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BStringUtil_ParseBString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseBString'
type BStringUtil_ParseBString_Call struct {
	*mock.Call
}

// ParseBString is a helper method to define mock.On call
//   - bString string
func (_e *BStringUtil_Expecter) ParseBString(bString interface{}) *BStringUtil_ParseBString_Call {
	return &BStringUtil_ParseBString_Call{Call: _e.mock.On("ParseBString", bString)}
}

func (_c *BStringUtil_ParseBString_Call) Run(run func(bString string)) *BStringUtil_ParseBString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *BStringUtil_ParseBString_Call) Return(_a0 *int64, _a1 error) *BStringUtil_ParseBString_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BStringUtil_ParseBString_Call) RunAndReturn(run func(string) (*int64, error)) *BStringUtil_ParseBString_Call {
	_c.Call.Return(run)
	return _c
}

// TimeStringSplit provides a mock function with given fields: scheduleString
func (_m *BStringUtil) TimeStringSplit(scheduleString string) []string {
	ret := _m.Called(scheduleString)

	var r0 []string
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(scheduleString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// BStringUtil_TimeStringSplit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TimeStringSplit'
type BStringUtil_TimeStringSplit_Call struct {
	*mock.Call
}

// TimeStringSplit is a helper method to define mock.On call
//   - scheduleString string
func (_e *BStringUtil_Expecter) TimeStringSplit(scheduleString interface{}) *BStringUtil_TimeStringSplit_Call {
	return &BStringUtil_TimeStringSplit_Call{Call: _e.mock.On("TimeStringSplit", scheduleString)}
}

func (_c *BStringUtil_TimeStringSplit_Call) Run(run func(scheduleString string)) *BStringUtil_TimeStringSplit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *BStringUtil_TimeStringSplit_Call) Return(_a0 []string) *BStringUtil_TimeStringSplit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BStringUtil_TimeStringSplit_Call) RunAndReturn(run func(string) []string) *BStringUtil_TimeStringSplit_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewBStringUtil interface {
	mock.TestingT
	Cleanup(func())
}

// NewBStringUtil creates a new instance of BStringUtil. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBStringUtil(t mockConstructorTestingTNewBStringUtil) *BStringUtil {
	mock := &BStringUtil{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
